name: Daily Price Scraper

on:
  schedule:
    - cron: "0 5 * * *"  # Every day at 5AM UTC
  workflow_dispatch:      # Manual trigger option

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Run daily scrape
        run: python main.py

      - name: Commit & Push updated data
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/latest_prices.csv logs/app.log || true
          git commit -m "Auto-update: daily scrape $(date)" || echo "No changes"
          git push || echo "Push skipped"
